### PR TITLE
flake8 fixes

### PR DESCRIPTION
**Pull request by Aniket21mathur**

### CODE REVIEW

**Comment by quozl** [comment]
Purpose of the flake8 warning about vague exception clause is to make sure that unrelated exceptions are not caught by accident.  BaseException is just as vague.

**Comment by Aniket21mathur** [comment]
Thanks. Please review the changes.

**Comment by quozl** [comment]
Reviewed, thanks.  Will you be resolving the remaining flake8 reports?

**Comment by Aniket21mathur** [comment]
>  Will you be resolving the remaining flake8 reports?

Thanks. I have fixed the remaining reports. I have not made any change to sugargame. Please review.

**Pull request merged**
