### PR TITLE
Port to Python3 + update to sugargame v1.3

### PR DESCRIPTION
**Pull request by ayushnawal**
@quozl , please review :grin:

### CODE REVIEW

**Comment by quozl** [comment]
Please finish porting; there are placeholder variables in argument lists inserted by 2to3.

Please rebase.

**Comment by ayushnawal** [comment]
Done :sweat_smile:

**Comment by quozl** [comment]
Oops, sorry, forgot to push.  Please rebase against _master_.

**Comment by ayushnawal** [comment]
Done

**Comment by quozl** [comment]
Thanks.  Used "Port to Python 3" as commit message to be consistent with others.

**Pull request merged**
