### PR TITLE
Fix: #1 Port to GTK+ 3 Sugar3 Toolkit

### PR DESCRIPTION
**Pull request by Pro-Panda**
**Fixed in PR**: #1 Port to GTK+ 3 and Sugar Toolkit for GTK+ 3

**Cases Tested:**
 - Player gets out initially
 - Player gets out after 1/3/4 chances
 - Changed level using speed_range bar
 - Stopped actvity

**Tested on**:
 - Packaged Environment(rdesktop)
 - Ubuntu 16.04

### CODE REVIEW

**Comment by Pro-Panda** [comment]
@quozl Kindly review.
Also, please point my mistakes in code style/PR/ commit style, so that I can improve

**Comment by quozl** [comment]
Thanks.  Tested 3ffd81c.

- [ ] sys.stderr has a PyGIWarning for activity.py:16 about Gtk version,
- [ ] the activity toolbar renders first, with the canvas rendered about a second later, on my fastest test system; they should render together,
- [ ] sys.stderr also has an AttributeError when changing speed, which causes set_delay not to be called; it doesn't get any faster even if asked.

Please also refer to https://github.com/sugarlabs/sugargame for authoritative sources of some of the files you've changed.  If you have tested changes the authoritative source should be updated.  Hope you didn't port them by hand.  I didn't check.  I've seen several ports recently, and it would make a mess if ports weren't sharing the code.

**Comment by Pro-Panda** [comment]
@quozl I was porting them on my own initially, but then I looked at other ports and used the same naming/coding conventions for functions, signals etc. Was there anything else to keep in mind as well ?
Also, do we need to 'use' something else while porting, as I am working on another right now

**Comment by quozl** [comment]
If you diverge from sugargame for a good reason, then also make a pull request to sugargame, thanks.

**Comment by Pro-Panda** [comment]
@quozl
Sorry, but I didn't fully understand the use of sugarname here.
It is to be used as the convention principle for writing the code, or is there something else as well.

**Comment by Pro-Panda** [comment]
@quozl 
Thanks. I figured out my mistake.

**Comment by quozl** [comment]
sugargame is a Python module which provides a merged event loop for Pygame and Gtk+.

https://github.com/sugarlabs/sugargame is the repository.  Also a Wiki page I think.

**Comment by Pro-Panda** [comment]
@quozl Kindly review
Fixed in 4c5af58:
 - [x] sys.stderr has a PyGIWarning for activity.py:16 about Gtk version,
 - [x] sys.stderr also has an AttributeError when changing speed, which causes set_delay not to be called; it doesn't get any faster even if asked.
 - [x] Using sugarname template in the code

**Tested**

**Problems:**
**1.** Couldn't reproduce this. Although I am digging into it, but please let me know if the problem still persists
  - [ ] the activity toolbar renders first, with the canvas rendered about a second later, on my fastest test system; they should render together

**2.** I am unclear as to what should be updated ?
> If you have tested changes the authoritative source should be updated

**Comment by Pro-Panda** [comment]
@quozl Kindly review
3e46e2e should fix this
 - [x] the activity toolbar renders first, with the canvas rendered about a second later, on my fastest test system; they should render together

**Note**: Since I couldn't reproduce the problem, I couldn't test it.

**Comment by quozl** [comment]
Neither 4c5af58 nor 3e46e2e fixes the problem of delayed rendering of the Pygame canvas.

What are you testing with?

Test method here is;
* Ubuntu 18.04 beta with Gtk+ 3.22.26 and Pygame 1.9.1,
* Start Sugar 0.112,
* Start Terminal; to capture sys.stderr cleanly,
* Start activity using `sugar-activity`.

Expected is simultaneous render of toolbar and canvas; that is, top line and rest of display.

Observed is render of toolbar, then a pause, then render of canvas.

**Comment by quozl** [comment]
Sorry, but it looks like the port was mostly done some time ago, and @walterbender had not merged it.

I've merged master from the gtk3 branch.

Please rebase your branch and resolve the differences, then we can continue working through the problems.  :grin:

**Comment by Pro-Panda** [comment]
Should I close this then ?

**Pull request closed without merging**
